version: "3"

volumes:
  database:
    driver: local

services:
  web:
    image: marinhomich/web
    container_name: web
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - mysql-compose-network
  mysql:
    platform: linux/amd64
    image: mysql:8.0.32
    container_name: turborepo_mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: turborepo
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    networks:
      - mysql-compose-network
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network
# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks: 
  mysql-compose-network:
    driver: bridge
